modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="indexer"
version="1.0.0"
displayName="Indexer"
authors="AgustinBenitez"
description='''An indexer to filter and organize container contents.'''

[[dependencies.indexer]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.indexer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"