modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="indexer"
version="1.0.7"
displayName="Indexer"
authors="AgustinBenitez"
logoFile="assets/indexer/textures/gui/logo.png"
description="Indexer is an advanced system for automatically filtering and organizing the contents of your chest/containers in Minecraft."

[[dependencies.indexer]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.indexer]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"